language: node_js
sudo: false

node_js:
  - "8"

services:
  - redis-server

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-4.8

notifications:
  email: false
